/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

/* Note: This file is machine generated, do not edit directly! */

package com.springrts.ai;


/**
 * These are the Java exposed enumerations.
 * We are not calling the engine, this is a pure Java class.
 *
 * @author	AWK wrapper script
 * @version	GENERATED
 */
public abstract class Enumerations {

	public enum CommandTopic {
		COMMAND_DRAWER_POINT_ADD(1),
		COMMAND_DRAWER_LINE_ADD(2),
		COMMAND_DRAWER_POINT_REMOVE(3),
		COMMAND_SEND_START_POS(4),
		COMMAND_CHEATS_SET_MY_INCOME_MULTIPLIER(5),
		COMMAND_SEND_TEXT_MESSAGE(6),
		COMMAND_SET_LAST_POS_MESSAGE(7),
		COMMAND_SEND_RESOURCES(8),
		COMMAND_SEND_UNITS(9),
		COMMAND_UNUSED_0(10),
		COMMAND_UNUSED_1(11),
		COMMAND_GROUP_CREATE(12),
		COMMAND_GROUP_ERASE(13),
		COMMAND_GROUP_ADD_UNIT(14),
		COMMAND_GROUP_REMOVE_UNIT(15),
		COMMAND_PATH_INIT(16),
		COMMAND_PATH_GET_APPROXIMATE_LENGTH(17),
		COMMAND_PATH_GET_NEXT_WAYPOINT(18),
		COMMAND_PATH_FREE(19),
		COMMAND_CHEATS_GIVE_ME_RESOURCE(20),
		COMMAND_CALL_LUA_RULES(21),
		COMMAND_DRAWER_ADD_NOTIFICATION(22),
		COMMAND_DRAWER_DRAW_UNIT(23),
		COMMAND_DRAWER_PATH_START(24),
		COMMAND_DRAWER_PATH_FINISH(25),
		COMMAND_DRAWER_PATH_DRAW_LINE(26),
		COMMAND_DRAWER_PATH_DRAW_LINE_AND_ICON(27),
		COMMAND_DRAWER_PATH_DRAW_ICON_AT_LAST_POS(28),
		COMMAND_DRAWER_PATH_BREAK(29),
		COMMAND_DRAWER_PATH_RESTART(30),
		COMMAND_DRAWER_FIGURE_CREATE_SPLINE(31),
		COMMAND_DRAWER_FIGURE_CREATE_LINE(32),
		COMMAND_DRAWER_FIGURE_SET_COLOR(33),
		COMMAND_DRAWER_FIGURE_DELETE(34),
		COMMAND_UNIT_BUILD(35),
		COMMAND_UNIT_STOP(36),
		COMMAND_UNIT_WAIT(37),
		COMMAND_UNIT_WAIT_TIME(38),
		COMMAND_UNIT_WAIT_DEATH(39),
		COMMAND_UNIT_WAIT_SQUAD(40),
		COMMAND_UNIT_WAIT_GATHER(41),
		COMMAND_UNIT_MOVE(42),
		COMMAND_UNIT_PATROL(43),
		COMMAND_UNIT_FIGHT(44),
		COMMAND_UNIT_ATTACK(45),
		COMMAND_UNIT_ATTACK_AREA(46),
		COMMAND_UNIT_GUARD(47),
		COMMAND_UNIT_AI_SELECT(48),
		COMMAND_UNIT_GROUP_ADD(49),
		COMMAND_UNIT_GROUP_CLEAR(50),
		COMMAND_UNIT_REPAIR(51),
		COMMAND_UNIT_SET_FIRE_STATE(52),
		COMMAND_UNIT_SET_MOVE_STATE(53),
		COMMAND_UNIT_SET_BASE(54),
		COMMAND_UNIT_SELF_DESTROY(55),
		COMMAND_UNIT_SET_WANTED_MAX_SPEED(56),
		COMMAND_UNIT_LOAD_UNITS(57),
		COMMAND_UNIT_LOAD_UNITS_AREA(58),
		COMMAND_UNIT_LOAD_ONTO(59),
		COMMAND_UNIT_UNLOAD_UNITS_AREA(60),
		COMMAND_UNIT_UNLOAD_UNIT(61),
		COMMAND_UNIT_SET_ON_OFF(62),
		COMMAND_UNIT_RECLAIM_UNIT(63),
		COMMAND_UNIT_RECLAIM_AREA(64),
		COMMAND_UNIT_CLOAK(65),
		COMMAND_UNIT_STOCKPILE(66),
		COMMAND_UNIT_D_GUN(67),
		COMMAND_UNIT_D_GUN_POS(68),
		COMMAND_UNIT_RESTORE_AREA(69),
		COMMAND_UNIT_SET_REPEAT(70),
		COMMAND_UNIT_SET_TRAJECTORY(71),
		COMMAND_UNIT_RESURRECT(72),
		COMMAND_UNIT_RESURRECT_AREA(73),
		COMMAND_UNIT_CAPTURE(74),
		COMMAND_UNIT_CAPTURE_AREA(75),
		COMMAND_UNIT_SET_AUTO_REPAIR_LEVEL(76),
		COMMAND_UNIT_SET_IDLE_MODE(77),
		COMMAND_UNIT_CUSTOM(78),
		COMMAND_CHEATS_GIVE_ME_NEW_UNIT(79),
		COMMAND_TRACE_RAY(80),
		COMMAND_PAUSE(81),
		COMMAND_UNIT_RECLAIM_FEATURE(82),
		COMMAND_DEBUG_DRAWER_GRAPH_SET_POS(83),
		COMMAND_DEBUG_DRAWER_GRAPH_SET_SIZE(84),
		COMMAND_DEBUG_DRAWER_GRAPH_LINE_ADD_POINT(85),
		COMMAND_DEBUG_DRAWER_GRAPH_LINE_DELETE_POINTS(86),
		COMMAND_DEBUG_DRAWER_GRAPH_LINE_SET_COLOR(87),
		COMMAND_DEBUG_DRAWER_GRAPH_LINE_SET_LABEL(88),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_ADD(89),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_UPDATE(90),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_DELETE(91),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_SET_POS(92),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_SET_SIZE(93),
		COMMAND_DEBUG_DRAWER_OVERLAYTEXTURE_SET_LABEL(94),
		COMMAND_TRACE_RAY_FEATURE(95),
		COMMAND_CALL_LUA_UI(96);

		private final int id;
		CommandTopic(int id) { this.id = id; }
		public int getValue() { return id; }
	}

	public enum UnitCommandOptions {
		UNIT_COMMAND_OPTION_INTERNAL_ORDER((1 << 3)),
		UNIT_COMMAND_OPTION_RIGHT_MOUSE_KEY((1 << 4)),
		UNIT_COMMAND_OPTION_SHIFT_KEY((1 << 5)),
		UNIT_COMMAND_OPTION_CONTROL_KEY((1 << 6)),
		UNIT_COMMAND_OPTION_ALT_KEY((1 << 7));

		private final int id;
		UnitCommandOptions(int id) { this.id = id; }
		public int getValue() { return id; }
	}
}

